### ISSUE TITLE
Program will not run

### ISSUE THREAD

**Issue by 19LBates** [fossie08/hareAndTortoise-v2#8]
**Describe the bug**
When the .exe file is opened, a cmd window opens briefly then closes. Nothing else happens afterwards.

**To Reproduce**
1. Download thr program
2. Follow the correct steps (adding the 'default.png' and 'animal.simulation' files)

**Expected behavior**
The program should run when opened

**Screenshots**
When the program is run via powershell:
![image](https://github.com/user-attachments/assets/c8487b0e-6f6f-4e21-bb21-1db78334a288)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version	10.0.22631 Build 22631

**Additional context**

**Comment by fossie08** [comment]
K, mb. Need to add some stuff to the animal.simulation file. This is a tempoary fix and will be sorted in the next release

1. Open the animal.simulation file in vs code
2. Add the following to it

`Name,Score,Min Speed,Max Speed,UUID`

so it looks like this
make sure to add the newline

![image](https://github.com/user-attachments/assets/8540d2f2-5f1a-4bc5-8876-da72c68921b7)

**Comment by 19LBates** [comment]
That still isn't working. It looks like it's trying to access files with paths from your computer. Such as `C:/Users/ollie/...`
